#!/usr/bin/env -S bash +x

# script run by `oj-verify`.

# $1 = contest/problem/Main.hs (example: abc350/f)
contest="$(dirname "$(dirname "$1")")"
problem="$(basename "$(dirname "$1")")"

cd "$contest"
cabal build "$problem-exe"

