#!/usr/bin/env bash -euE

cd "$(dirname "$0")"

dir="$1"

if [ -e "$dir" ] ; then
    echo "Exists: $dir"
    exit
fi

cp -r _template "$dir"

cd "$dir"

cat package.yaml | sed "s/template/$1/" | tee package.yaml > /dev/null

mv 'app/template.hs' 'app/P01.hs'

nums() {
    seq 1 10 | xargs -I{} printf '%02d\n' '{}'
}

for n in $(nums | sed 1d) ; do
    cp 'app/P01.hs' "app/P$n.hs"
done

for n in $(nums) ; do
    : > "app/P$n-input"
done

