#!/usr/bin/env bash
set -euE

acc='acc' # 'npx acc'

$acc new "$1" --template ${2:-haskell} --choice all
# mkdir "$1"

# NOTE: Package name can include up to one `-`, so delete `_` all
contest="$1"
package="$(printf '%s' "$contest" | sed 's/_//g')"

# cabal
cat _acc/_acc.cabal | sed "s;_acc;$package;g" > "$contest/$package.cabal"
cat _acc/cabal.project | sed "s;_acc;$package;g" > "$contest/cabal.project"

cd "$contest"

# Emacs
: > ".projectile"

# patch source files to embed `verifycation-helper` contest IDs:
for f in $(command ls */*.hs) ; do
  # Example: <<url>> -> https://atcoder.jp/contests/abc294/tasks/abc294_b
  problem="$(dirname "$(printf '%s' "$f")")"
  echo "patching $contest, $problem .." 2>&1
  # cat "$f" | sed "s@<<url>>@https://atcoder.jp/contests/$contest/tasks/${contest}_$problem@g" | tee "$f" > /dev/null
  res="$(cat "$f" | sed "s@<<url>>@https://atcoder.jp/contests/$contest/tasks/${contest}_$problem@g")"
  printf '%s' "$res" > "$f"
done

gen-hie > hie.yaml

