#!/usr/bin/env bash
set -euE

acc='acc' # 'npx acc'

$acc new "$1" --template haskell --choice all
# mkdir "$1"

# For HLS
# cat _acc/hie.yaml | sed "s;_acc;$1;g" > "$1/hie.yaml"

# stack
package_name="$(printf '%s' "$1" | sed 's/_/-/g')"

# cabal
cat _acc/_acc.cabal | sed "s;_acc;$1;g" > "$1/$1.cabal"
cat _acc/cabal.project | sed "s;_acc;$1;g" > "$1/cabal.project"

cd "$1"

# Emacs
: > ".projectile"

# patch source files to embed `verifycation-helper` contest IDs:
for f in $(command ls */*.hs) ; do
  # Example: <<url>> -> https://atcoder.jp/contests/abc294/tasks/abc294_b
  contest="$1"
  problem="$(dirname "$(printf '%s' "$f")")"
  echo "patching $contest, $problem .." 2>&1
  # cat "$f" | sed "s@<<url>>@https://atcoder.jp/contests/$contest/tasks/${contest}_$problem@g" | tee "$f" > /dev/null
  res="$(cat "$f" | sed "s@<<url>>@https://atcoder.jp/contests/$contest/tasks/${contest}_$problem@g")"
  printf '%s' "$res" > "$f"
done

gen-hie > hie.yaml

