= {acc} configuration files
:acc: https://github.com/Tatamo/atcoder-cli[atcoder-cli]
:oj: https://github.com/online-judge-tools/oj[online-judge-tools]
:ghcs-nix: https://gitlab.haskell.org/bgamari/ghcs-nix[ghcs-nix]
:direnv: https://direnv.net/[direnv]
:ghcup: https://www.haskell.org/ghcup/[GHCup]
:implicit-hie: https://hackage.haskell.org/package/implicit-hie[implicit-hie]

The configuration files are located at `npx acc config-dir`.

== Installation

Install {acc} and {oj}:

[source,sh]
----
$ # I use local install (for NixOS):
$ npm install atcoder-cli
$ python3 -m pip install online-judge-tools
----

== Configuration

Set up `config.yaml`:

[source,sh]
----
$ # Download all problems by default
$ npx acc config default-task-choice all

$ # Test directories are named as `test-cases`
$ npx acc config default-test-dirname-format test-cases

$ # Use `haskell` template as default
$ npx acc config default-template haskell
----

Add `haskell` template:

[source,sh]
----
$ bash -c 'ln -s "$(pwd)/haskell" "$(npx acc config-dir)"'
----

== Language server support

You do need the language server support! If it's not working, check out the following steps.

=== Installation

Your have to have GHC 9.4.5 and HLS 2.2.0 in your `PATH`.

* Use GHCup to install GHC, HLS, Stack and Cabal.
* Use {direnv} to overwrite your binaries in your `PATH`.

=== Installation  (NixOS)

`nix-direnv` + the following `flake.nix` at least works:

[source,nix]
----
{
  description = "A basic flake with a shell";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        devShells.default = with pkgs; mkShell {
          nativeBuildInputs = [
            pkg-config
            stack
            cabal-install
            llvmPackages.bintools
          ];

          packages = [
            # atcoder-cli is from npm

            # NOTE: update `oj-path` everytime you update `online-judge-tools`
            online-judge-tools
            python311Packages.selenium
            nodejs

            hlint
            haskell.compiler.ghc945
            (haskell-language-server.override { supportedGhcVersions = [ "945" ]; })
            haskellPackages.hoogle
            haskellPackages.ghcid
            haskellPackages.ghcide
          ];
        };
      });
}
----

=== Project detection

HLS have to run with the root directory `abc278` (for example), not `abc-hs`.

I'm using `.projectile` file for indicating the root directory for Emacs. You might need another
file or hack depending on your editor.

=== Proiject files

- Make sure you have correct `package.yaml` with a correct `exectuables` section.
- Make sure you have `hie.yaml`, which can be generated with {implicit-hie}.

